name: Branch Cleanup

on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run cleanup script
      run: python github_branch_cleanup.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
